# Generated by Django 4.0.1 on 2022-02-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bestdeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.FileField(default='profile_pics/default.jpg', upload_to='profile_pics/')),
                ('description', models.CharField(max_length=100)),
                ('description2', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Headphone',
        ),
        migrations.DeleteModel(
            name='Iphone',
        ),
        migrations.DeleteModel(
            name='Laptop',
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
