# Generated by Django 4.0.1 on 2022-02-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_bestdeal_delete_headphone_delete_iphone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='crno',
            field=models.BigIntegerField(),
        ),
    ]
