# Generated by Django 4.0.1 on 2022-03-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='order',
        ),
        migrations.DeleteModel(
            name='Saveuser',
        ),
    ]
